Fix Roslyn build version * crap
https://stackoverflow.com/a/46985624/105929

```
Properties\GlobalAssemblyInfo.cs(14,28): Error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]]
```